### ISSUE TITLE
Support Gradle configuration cache

### ISSUE THREAD

**Issue by AlexKrupa** [MiSikora/laboratory#276]
[Configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) is an incubating Gradle feature that, well, caches configuration.

Running a task with configuration caching (Gradle 7.4.2) reports the following problems:
```sh
> ./gradlew --configuration-cache --configuration-cache-problems=warn :app:assembleDebug

...

> Configure project :app
2 problems were found storing the configuration cache.
- Task `:app:generateFeatureFactory` of type `io.mehow.laboratory.gradle.FeatureFactoryTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:generateFeatureFlags` of type `io.mehow.laboratory.gradle.FeatureFlagsTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

...
```

The documentation specifies [requirements for configuration cache to work](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements).

**Comment by MiSikora** [comment]
Yeah, I've been meaning to migrate this project to use the proper injection and so on. Definitely something I should prioritize and just do.

**Comment by AlexKrupa** [comment]
Amazing, thanks for the fast reaction! I couldn't have wished for a better OSS-consumer experience. 😄
