### ISSUE TITLE
Possibility to set custom style for option items or toggle compact mode

### ISSUE THREAD

**Issue by vudzkostek** [MiSikora/laboratory#82]
When having multiple (20 or more flags) it gets harder to find option that we are interested in.
Would be nice if we could set custom layout for experiment item, or if there would be some predefined compact layout that we could enable in LaboratoryActivity configuration.

Related to issue: https://github.com/MiSikora/laboratory/issues/81

**Comment by MiSikora** [comment]
It can already be customised to some extent by providing a different theme to `LaboratoryActivity`.

https://github.com/MiSikora/laboratory/blob/e6db7fb3b5a47449a0ad66891376dc431e076758/sample/src/main/AndroidManifest.xml#L20-L26

Layouts use predefined Material attributes so you can substitute them in the theme.

As far as the full customisation goes it's not something that I want to maintain. The only thing that I could help with is to move presentation layer to a separate module so you can write your own UI and connect it to the available presenter. Would that help you or overriding theme is enough?

**Comment by vudzkostek** [comment]
I think that solution in https://github.com/MiSikora/laboratory/issues/81 will resolve this as "grouping" will help with readability
